spring:
  application:
    name: dubbo-sentinel-provider
#
#demo:
#  service:
#    version: 1.0.0

embedded:
  zookeeper:
    port: 2181

dubbo:
#  scan:
#    base-packages: net.yiyutao.dubbo.sentinel.service
  registry:
    address: zookeeper://127.0.0.1:${embedded.zookeeper.port}
  protocol:
    name: dubbo
    port: 20880
#    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache